import { Place, WanderList, ListPlace } from '@/types/database';

export const CURATED_PLACES: Place[] = [
  {
    id: 'place-kyoto-1',
    name: 'Wabi Secret Tea Pavilion',
    slug: 'wabi-secret-tea-pavilion',
    location: 'Kyoto',
    city: 'Kyoto',
    country: 'Japan',
    category: 'Hidden Gem',
    tags: ['Tea House', 'Matcha', 'Garden', 'Historic'],
    address: 'Higashiyama Ward, Kyoto 605-0000, Japan',
    description: 'A serene centuries-old tea house hidden behind a mossy wooden gate. Renowned for single-estate ceremonial matcha, fresh seasonal wagashi, and peaceful stone garden views.',
    website: 'https://kyoto.travel',
    rating: 4.9,
    lat: 35.0037,
    lng: 135.7772,
    maps_url: 'https://maps.google.com/?q=Higashiyama+Ward+Kyoto+Japan',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 184,
    downvotes_count: 2,
    community_score: 195,
    lists_count: 4,
    is_saved: false,
  },
  {
    id: 'place-kyoto-2',
    name: 'Sagano Bamboo Grove Path',
    slug: 'sagano-bamboo-grove-path',
    location: 'Arashiyama, Kyoto',
    city: 'Kyoto',
    country: 'Japan',
    category: 'Nature',
    tags: ['Scenic View', 'Nature', 'Morning Walk', 'Must Visit'],
    address: 'Arashiyama, Ukyo Ward, Kyoto, Japan',
    description: 'An iconic, towering natural bamboo forest pathway. In the early morning hours, the soft sunlight filters through emerald stalks accompanied by the calming rustle of the wind.',
    website: 'https://kyoto.travel',
    rating: 4.8,
    lat: 35.017,
    lng: 135.6713,
    maps_url: 'https://maps.google.com/?q=Arashiyama+Bamboo+Grove+Kyoto',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 312,
    downvotes_count: 5,
    community_score: 320,
    lists_count: 6,
    is_saved: false,
  },
  {
    id: 'place-kyoto-3',
    name: '% Arabica Kyoto Higashiyama',
    slug: 'arabica-kyoto-higashiyama',
    location: 'Higashiyama, Kyoto',
    city: 'Kyoto',
    country: 'Japan',
    category: 'Café',
    tags: ['Specialty Coffee', 'Espresso', 'Design', 'Scenic View'],
    address: '87-5 Hoshinocho, Higashiyama Ward, Kyoto 605-0853, Japan',
    description: 'World-famous minimalist roastery situated right by the historic Yasaka Pagoda. Masterfully poured Spanish lattes with unforgettable traditional street vistas.',
    website: 'https://arabica.coffee',
    rating: 4.7,
    lat: 34.9984,
    lng: 135.7797,
    maps_url: 'https://maps.google.com/?q=Arabica+Kyoto+Higashiyama',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 245,
    downvotes_count: 8,
    community_score: 250,
    lists_count: 5,
    is_saved: false,
  },
  {
    id: 'place-kyoto-4',
    name: 'Gion Duck Noodles',
    slug: 'gion-duck-noodles',
    location: 'Gion, Kyoto',
    city: 'Kyoto',
    country: 'Japan',
    category: 'Food',
    tags: ['Ramen', 'Duck Broth', 'Secret Spot', 'Late Dinner'],
    address: 'Gionmachi Kitagawa, Higashiyama Ward, Kyoto, Japan',
    description: 'A discreet alleyway noodle den marked only by a neon duck emoji. Serves concentrated smoked duck broth ramen garnished with seasonal sansho pepper.',
    website: null,
    rating: 4.9,
    lat: 35.0041,
    lng: 135.7761,
    maps_url: 'https://maps.google.com/?q=Gionmachi+Kitagawa+Higashiyama+Kyoto',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 276,
    downvotes_count: 3,
    community_score: 285,
    lists_count: 4,
    is_saved: false,
  },
  {
    id: 'place-kolkata-1',
    name: 'Princep Ghat Riverbank',
    slug: 'princep-ghat-riverbank',
    location: 'Strand Rd, Kolkata',
    city: 'Kolkata',
    country: 'India',
    category: 'Sightseeing',
    tags: ['Sunset', 'Heritage', 'Riverbank', 'Romantic'],
    address: 'Strand Rd, Vidyasagar Setu, Kolkata, West Bengal 700021, India',
    description: 'Historic Greek monument overlooking the majestic Hooghly River. Famous for traditional wooden boat rides during golden hour while the grand Vidyasagar Setu illuminates overhead.',
    website: null,
    rating: 4.8,
    lat: 22.5558,
    lng: 88.3328,
    maps_url: 'https://maps.google.com/?q=Princep+Ghat+Kolkata',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 289,
    downvotes_count: 4,
    community_score: 300,
    lists_count: 5,
    is_saved: false,
  },
  {
    id: 'place-kolkata-2',
    name: 'Blue Tokai Roastery — Park St',
    slug: 'blue-tokai-roastery-park-st',
    location: 'Park Street, Kolkata',
    city: 'Kolkata',
    country: 'India',
    category: 'Café',
    tags: ['Coffee Roaster', 'Sourdough', 'Work Spot', 'Artisan'],
    address: 'Park Street area, Kolkata, West Bengal 700016, India',
    description: 'Third-wave specialty coffee roaster featuring single-origin Indian estate brews, cold brews, handmade sourdough croissants, and a bright calming workspace.',
    website: 'https://bluetokaicoffee.com',
    rating: 4.7,
    lat: 22.5535,
    lng: 88.3524,
    maps_url: 'https://maps.google.com/?q=Park+Street+Kolkata',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 215,
    downvotes_count: 6,
    community_score: 225,
    lists_count: 4,
    is_saved: false,
  },
  {
    id: 'place-kolkata-3',
    name: 'College Street Heritage Books',
    slug: 'college-street-heritage-books',
    location: 'College Street, Kolkata',
    city: 'Kolkata',
    country: 'India',
    category: 'Hidden Gem',
    tags: ['Vintage Books', 'Heritage', 'Intellectual', 'Alleyway'],
    address: 'College Street (Boi Para), Kolkata 700073, India',
    description: 'The largest second-hand book market in the world spanning nearly a mile of wooden book kiosks, adjacent to the historic 1942 Indian Coffee House.',
    website: null,
    rating: 4.9,
    lat: 22.5744,
    lng: 88.3639,
    maps_url: 'https://maps.google.com/?q=College+Street+Kolkata',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 340,
    downvotes_count: 3,
    community_score: 355,
    lists_count: 6,
    is_saved: false,
  },
  {
    id: 'place-kolkata-4',
    name: 'Sienna Store & Cafe',
    slug: 'sienna-store-cafe',
    location: 'Hindustan Park, Kolkata',
    city: 'Kolkata',
    country: 'India',
    category: 'Restaurants',
    tags: ['Farm-to-Table', 'Ceramics', 'Brunch', 'Design'],
    address: '49, Hindustan Park, Gariahat, Kolkata 700029, India',
    description: 'A charming sanctuary combining handcrafted Santiniketan studio ceramics with an inventive farm-to-table seasonal kitchen. Celebrated for Gondhoraj salads and avocado toasts.',
    website: 'https://sienastore.in',
    rating: 4.8,
    lat: 22.5186,
    lng: 88.3619,
    maps_url: 'https://maps.google.com/?q=Sienna+Store+and+Cafe+Kolkata',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 310,
    downvotes_count: 4,
    community_score: 320,
    lists_count: 5,
    is_saved: false,
  },
  {
    id: 'place-paris-1',
    name: 'Du Pain et des Idées',
    slug: 'du-pain-et-des-idees',
    location: '10th Arrondissement, Paris',
    city: 'Paris',
    country: 'France',
    category: 'Food',
    tags: ['Boulangerie', 'Pastries', 'Escargot Pistache', 'Heritage'],
    address: '34 Rue Yves Toudic, 75010 Paris, France',
    description: 'An acclaimed 1875 historic bakery near Canal Saint-Martin. Famous across the globe for their Escargot Pistache-Chocolat pastry and Pain des Amis sourdough crusts.',
    website: 'https://dupainetdesidees.com',
    rating: 4.9,
    lat: 48.8712,
    lng: 2.3619,
    maps_url: 'https://maps.google.com/?q=34+Rue+Yves+Toudic+75010+Paris',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 410,
    downvotes_count: 6,
    community_score: 425,
    lists_count: 7,
    is_saved: false,
  },
  {
    id: 'place-paris-2',
    name: 'Boot Café',
    slug: 'boot-cafe',
    location: 'Le Marais, Paris',
    city: 'Paris',
    country: 'France',
    category: 'Café',
    tags: ['Specialty Coffee', 'Micro Cafe', 'Le Marais', 'Historic'],
    address: '19 Rue du Pont aux Choux, 75003 Paris, France',
    description: 'Housed in an enchanting 19th-century blue cobbler shop (Cordonnerie), Boot Café is one of Paris’s coziest espresso bars crafting exceptional flat whites.',
    website: null,
    rating: 4.7,
    lat: 48.8617,
    lng: 2.3662,
    maps_url: 'https://maps.google.com/?q=19+Rue+du+Pont+aux+Choux+75003+Paris',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 260,
    downvotes_count: 5,
    community_score: 270,
    lists_count: 4,
    is_saved: false,
  },
  {
    id: 'place-paris-3',
    name: 'Septime La Cave',
    slug: 'septime-la-cave',
    location: '11th Arrondissement, Paris',
    city: 'Paris',
    country: 'France',
    category: 'Bars & Nightlife',
    tags: ['Natural Wine', 'Small Plates', 'Aperitif', 'Atmosphere'],
    address: '3 Rue Basfroi, 75011 Paris, France',
    description: 'An intimate standing-room natural wine cellar by the creators of Michelin-starred Septime. Exceptional pet-nats, artisanal charcuterie, and warm neighbourhood hospitality.',
    website: 'https://septime-charonne.fr',
    rating: 4.8,
    lat: 48.8538,
    lng: 2.3804,
    maps_url: 'https://maps.google.com/?q=3+Rue+Basfroi+75011+Paris',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 375,
    downvotes_count: 4,
    community_score: 390,
    lists_count: 5,
    is_saved: false,
  },
  {
    id: 'place-amalfi-1',
    name: 'Villa Cimbrone Infinity Terrace',
    slug: 'villa-cimbrone-infinity-terrace',
    location: 'Ravello, Amalfi Coast',
    city: 'Amalfi Coast',
    country: 'Italy',
    category: 'Sightseeing',
    tags: ['Infinite Vista', 'Mediterranean', 'Cliff Drop', 'Must Visit'],
    address: 'Via Santa Chiara 26, 84010 Ravello SA, Italy',
    description: 'Perched high above the azure Mediterranean, the Terrazza dell’Infinito is lined with neoclassical marble busts offering arguably the most breathtaking coastal view in Europe.',
    website: 'https://hotelvillacimbrone.com',
    rating: 4.9,
    lat: 40.6473,
    lng: 14.6115,
    maps_url: 'https://maps.google.com/?q=Villa+Cimbrone+Ravello+Italy',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 480,
    downvotes_count: 7,
    community_score: 495,
    lists_count: 6,
    is_saved: false,
  },
  {
    id: 'place-amalfi-2',
    name: 'Fiordo di Furore Cove',
    slug: 'fiordo-di-furore-cove',
    location: 'Furore, Amalfi Coast',
    city: 'Amalfi Coast',
    country: 'Italy',
    category: 'Nature',
    tags: ['Sea Fjord', 'Swimming', 'Hidden Cove', 'Arch Bridge'],
    address: 'Via Marina di Praia, 84010 Furore SA, Italy',
    description: 'A dramatic natural sea fjord tucked underneath a soaring arched highway bridge. Crystal clear turquoise water and colourful traditional fishing boats on pebble shores.',
    website: null,
    rating: 4.8,
    lat: 40.6152,
    lng: 14.5498,
    maps_url: 'https://maps.google.com/?q=Fiordo+di+Furore+Italy',
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    upvotes_count: 390,
    downvotes_count: 5,
    community_score: 400,
    lists_count: 5,
    is_saved: false,
  },
];

export const CURATED_LISTS: WanderList[] = [
  {
    id: 'list-kyoto-1',
    owner_id: 'user-elena',
    title: '7 Days in Kyoto: Cafés & Bamboo Groves',
    description: 'Slow-travel guide to Kyoto including hidden tea houses, morning bamboo paths, and artisan ramen alleys.',
    destination: 'Kyoto, Japan',
    cover_image: null,
    slug: '7-days-in-kyoto-cafes-bamboo-groves',
    is_public: true,
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    places_count: 4,
    votes_count: 18,
    is_saved: false,
    owner: {
      id: 'user-elena',
      display_name: 'Elena Rostova',
      username: 'elena_travels',
      bio: 'Slow traveler & coffee lover based in Tokyo & Kyoto.',
      avatar_url: null,
      location: 'Kyoto, Japan',
      created_at: '2026-01-01T00:00:00.000Z',
      updated_at: '2026-01-01T00:00:00.000Z',
      public_lists_count: 4,
      followers_count: 142,
    },
  },
  {
    id: 'list-kolkata-1',
    owner_id: 'user-aarav',
    title: 'Best Hidden Cafés in Kolkata',
    description: 'Colonial charm meets third-wave coffee culture across North & South Kolkata heritage spots.',
    destination: 'Kolkata, India',
    cover_image: null,
    slug: 'best-hidden-cafes-in-kolkata',
    is_public: true,
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    places_count: 4,
    votes_count: 24,
    is_saved: false,
    owner: {
      id: 'user-aarav',
      display_name: 'Aarav Mehta',
      username: 'aarav_explores',
      bio: 'Architectural photographer capturing heritage corners of India.',
      avatar_url: null,
      location: 'Kolkata, India',
      created_at: '2026-01-01T00:00:00.000Z',
      updated_at: '2026-01-01T00:00:00.000Z',
      public_lists_count: 6,
      followers_count: 210,
    },
  },
  {
    id: 'list-paris-1',
    owner_id: 'user-claire',
    title: 'Paris Pastries & Bistro Wine Guide',
    description: 'Authentic Parisian bakeries, natural wine caves, and classic cobblestone neighborhood bistros.',
    destination: 'Paris, France',
    cover_image: null,
    slug: 'paris-food-bucket-list-pastries-bistro-wine',
    is_public: true,
    created_at: '2026-01-10T10:00:00.000Z',
    updated_at: '2026-01-10T10:00:00.000Z',
    places_count: 3,
    votes_count: 31,
    is_saved: false,
    owner: {
      id: 'user-claire',
      display_name: 'Claire Dubois',
      username: 'claire_paris',
      bio: 'Food writer & sourdough baker roaming Paris arrondissements.',
      avatar_url: null,
      location: 'Paris, France',
      created_at: '2026-01-01T00:00:00.000Z',
      updated_at: '2026-01-01T00:00:00.000Z',
      public_lists_count: 5,
      followers_count: 340,
    },
  },
];

export const CURATED_LIST_PLACES_MAP: Record<string, ListPlace[]> = {
  'list-kyoto-1': [
    {
      id: 'lp-k-1',
      list_id: 'list-kyoto-1',
      place_id: 'place-kyoto-1',
      note: 'Elena: Hidden behind a wooden garden gate. The iced ceremonial matcha is unmatched.',
      priority: 'must_visit',
      status: 'visited',
      added_by: 'user-elena',
      created_at: '2026-01-10T10:00:00.000Z',
      updated_at: '2026-01-10T10:00:00.000Z',
      place: CURATED_PLACES[0],
      votes_count: 14,
      upvotes_count: 14,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-k-2',
      list_id: 'list-kyoto-1',
      place_id: 'place-kyoto-2',
      note: 'Kenji: Reach by 7:15 AM before tour groups to experience the true serene atmosphere.',
      priority: 'must_visit',
      status: 'planned',
      added_by: 'user-elena',
      created_at: '2026-01-10T10:05:00.000Z',
      updated_at: '2026-01-10T10:05:00.000Z',
      place: CURATED_PLACES[1],
      votes_count: 19,
      upvotes_count: 19,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-k-3',
      list_id: 'list-kyoto-1',
      place_id: 'place-kyoto-3',
      note: 'Claire: Spanish Latte on the stone steps overlooking Yasaka Pagoda.',
      priority: 'must_visit',
      status: 'saved',
      added_by: 'user-elena',
      created_at: '2026-01-10T10:10:00.000Z',
      updated_at: '2026-01-10T10:10:00.000Z',
      place: CURATED_PLACES[2],
      votes_count: 11,
      upvotes_count: 11,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-k-4',
      list_id: 'list-kyoto-1',
      place_id: 'place-kyoto-4',
      note: 'Marcus: Look for the small duck emoji neon sign. Exceptional smoked duck ramen.',
      priority: 'must_visit',
      status: 'saved',
      added_by: 'user-elena',
      created_at: '2026-01-10T10:15:00.000Z',
      updated_at: '2026-01-10T10:15:00.000Z',
      place: CURATED_PLACES[3],
      votes_count: 16,
      upvotes_count: 16,
      downvotes_count: 0,
      user_has_voted: false,
    },
  ],
  'list-kolkata-1': [
    {
      id: 'lp-kol-1',
      list_id: 'list-kolkata-1',
      place_id: 'place-kolkata-1',
      note: 'Aarav: Best at 5 PM golden hour for peaceful wooden boat rides.',
      priority: 'must_visit',
      status: 'visited',
      added_by: 'user-aarav',
      created_at: '2026-01-10T10:00:00.000Z',
      updated_at: '2026-01-10T10:00:00.000Z',
      place: CURATED_PLACES[4],
      votes_count: 22,
      upvotes_count: 22,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-kol-2',
      list_id: 'list-kolkata-1',
      place_id: 'place-kolkata-2',
      note: 'Elena: Single-origin pour-over paired with a fresh warm sourdough croissant.',
      priority: 'must_visit',
      status: 'saved',
      added_by: 'user-aarav',
      created_at: '2026-01-10T10:05:00.000Z',
      updated_at: '2026-01-10T10:05:00.000Z',
      place: CURATED_PLACES[5],
      votes_count: 15,
      upvotes_count: 15,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-kol-3',
      list_id: 'list-kolkata-1',
      place_id: 'place-kolkata-3',
      note: 'Ria: Vintage wooden book stalls where poets and Nobel laureates debated.',
      priority: 'must_visit',
      status: 'saved',
      added_by: 'user-aarav',
      created_at: '2026-01-10T10:10:00.000Z',
      updated_at: '2026-01-10T10:10:00.000Z',
      place: CURATED_PLACES[6],
      votes_count: 28,
      upvotes_count: 28,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-kol-4',
      list_id: 'list-kolkata-1',
      place_id: 'place-kolkata-4',
      note: 'Samir: Incredible ceramic shop upstairs and seasonal avocado bowls below.',
      priority: 'must_visit',
      status: 'planned',
      added_by: 'user-aarav',
      created_at: '2026-01-10T10:15:00.000Z',
      updated_at: '2026-01-10T10:15:00.000Z',
      place: CURATED_PLACES[7],
      votes_count: 18,
      upvotes_count: 18,
      downvotes_count: 0,
      user_has_voted: false,
    },
  ],
  'list-paris-1': [
    {
      id: 'lp-par-1',
      list_id: 'list-paris-1',
      place_id: 'place-paris-1',
      note: 'Claire: The Escargot Pistache straight out of the 1875 oven is legendary.',
      priority: 'must_visit',
      status: 'visited',
      added_by: 'user-claire',
      created_at: '2026-01-10T10:00:00.000Z',
      updated_at: '2026-01-10T10:00:00.000Z',
      place: CURATED_PLACES[8],
      votes_count: 35,
      upvotes_count: 35,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-par-2',
      list_id: 'list-paris-1',
      place_id: 'place-paris-2',
      note: 'Marcus: Paris’s smallest specialty coffee shop tucked into a 19th-century cobbler store.',
      priority: 'must_visit',
      status: 'saved',
      added_by: 'user-claire',
      created_at: '2026-01-10T10:05:00.000Z',
      updated_at: '2026-01-10T10:05:00.000Z',
      place: CURATED_PLACES[9],
      votes_count: 21,
      upvotes_count: 21,
      downvotes_count: 0,
      user_has_voted: false,
    },
    {
      id: 'lp-par-3',
      list_id: 'list-paris-1',
      place_id: 'place-paris-3',
      note: 'Samir: Natural orange wines paired with smoked ricotta and warm baguettes.',
      priority: 'must_visit',
      status: 'planned',
      added_by: 'user-claire',
      created_at: '2026-01-10T10:10:00.000Z',
      updated_at: '2026-01-10T10:10:00.000Z',
      place: CURATED_PLACES[10],
      votes_count: 29,
      upvotes_count: 29,
      downvotes_count: 0,
      user_has_voted: false,
    },
  ],
};
